[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/kitty.toml"
]

[window]
padding = {x = 5, y = 5}

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 9